### ISSUE TITLE
chapter2.mlx throws warnings

### ISSUE THREAD

**Issue by remo-pillat** [petercorke/RVC3-MATLAB#2]
**What environment are you using**

GitHub action running `tChapter2` unit test.
See log here: https://github.com/petercorke/RVC3-MATLAB/actions/runs/5456401781/jobs/9929160443

@petercorke, it also looks like the output from running chapter2.mlx is slightly different from what's in the book (e.g. when running line = S.line()), so that might be a bug in the `Twist` class.

**MATLAB Release**
R2023a (that's what the GitHub action is using)

**Describe the bug**

When running chapter2.mlx in a unit test in a GitHub action, I see the following warning twice:

  [Warning: line does not intersect the plot volume] 
  [> In Plucker/plot (line 568)

This happens on line 131 and line 163 in the MLX file.

**To Reproduce**
Run chapter2.mlx

**Expected behavior**
No warnings

**Comment by petercorke** [comment]
This was an error in `Twist.line`, passing `(v,w)` to the `Plucker` constructor rather than `(w,v)`.  Hopefully this is the end of the rotation, translation swap consequences for 6-vectors.
