### ISSUE TITLE
symbolic operation

### ISSUE THREAD

**Issue by amiao1017** [petercorke/RVC3-MATLAB#4]
hello， the RVC3-matlab dose not support symbolic operation. For example:

>> rotmx(theta)
 
ans =
 
[1,          0,           0]
[0, cos(theta), -sin(theta)]
[0, sin(theta),  cos(theta)]

this one is ok, but for so3, se3, Twist and so on, it can't work.

Do you have any plans to carry out this update, which is very important for the kinematics and dynamics research of robots

**Comment by petercorke** [comment]
The functions so3, se3 are part of core MATLAB, and their support for symbolics is a MathWorks decision not ours.  Twist uses se3 internally and so it inherits the limitation.

Either stick with native matrices, or try the older Robotics Toolbox for MATLAB on my GitHub but unfortunately that's no longer being maintained.
